from pandas import DataFrame
import numpy as np
from scipy.stats import skew

def get_filtered_program_logs(*, filtered_ids: dict[str, list[str]], **kwargs) -> DataFrame:
    """Gets the list of program logs based on a list of filtered participantids or programlogids

    Args:
        filtered_ids (dict[str, list[str]]): A dictionary containing referencing either a list of participantids or programlogids to filter by.
        If the dictionary contains neither of these, the whole program logs DataFrame is returned (nothing is filtered)

    Returns:
        DataFrame: Filtered rows of the program_logs table.
    """
    program_logs = kwargs["program_logs"]
    if "participantids" in filtered_ids:
        filtered_program_logs = program_logs[program_logs["participantid"].isin(filtered_ids["participantids"])]
    elif "programlogids" in filtered_ids:
        filtered_program_logs = program_logs[program_logs["id"].isin(filtered_ids["programlogids"])]
    else:
        filtered_program_logs = program_logs
    return filtered_program_logs


def get_uncoded_attempted_runs(**kwargs) -> list[int]:
    """Function to be discarded after analysis. Used to identify which valid exercise attempts haven't currently been coded with anything"""
    all_program_log_ids = set(kwargs["program_logs"]["id"])
    coded_program_log_ids = set(kwargs["coded_program_logs"]["program_log_id"])
    uncoded_program_log_ids = [id for id in all_program_log_ids if id not in coded_program_log_ids]
    return uncoded_program_log_ids


def get_missing_first_run_codes(**kwargs) -> list[int]:
    """Function used to check every attempted exercise has a first run code associated with it"""
    all_program_log_ids = set(kwargs["program_logs"]["id"])
    codes_to_check = []
    coded_program_logs_frame = kwargs["coded_program_logs"]
    for id in all_program_log_ids:
        set_of_codes = coded_program_logs_frame.loc[coded_program_logs_frame["program_log_id"] == id]["code_name"].values.tolist()
        if "Ran code before making changes" not in set_of_codes and "Made changes before running code" not in set_of_codes and "Didn't attempt exercise" not in set_of_codes:
            codes_to_check.append(id)
    return codes_to_check

def quartiles_for_exercise(values_per_exercise:list[list[int] | list[float]]) -> list[list[int]]: #TODO: Test out
    """Condenses the list of values (generated by some stats function) for each exercise (as well as all the exercises) into a smaller list representing the interquartile range.
    Helps to give an impression of how the data is distributed

    Args:
        values_per_exercise (list[list[int]  |  list[float]]): The list of values calculated for each attempted exercise. List of 6 lists, with the final one contaning values from every exercise

    Returns:
        list[list[int]]: A list of 6 lists each containing the interquartile range values. That is, lower bound, Q1, Q2, Q3, and upper bound. Allows a box plot to be generated
    """
    distributions_per_exercise = []

    for i in range(6):
        if values_per_exercise[i] != []:
            distributions_per_exercise.append([min(values_per_exercise[i]),
                                            np.percentile(values_per_exercise[i], 25),
                                            np.percentile(values_per_exercise[i], 50),
                                            np.percentile(values_per_exercise[i], 75),
                                            max(values_per_exercise[i])])
        else:
            #Adds an empty list if there are no entries in the total_times_per_exercises for a given exercise
            #i.e. if none of the list of participants had attempted a given exercise
            distributions_per_exercise.append([])
    return distributions_per_exercise

def skewness_for_exercises(values_per_exercise:list[list[int] | list[float]]) -> list[int]:
    """Condenses the list of values (generated by some stats function) for each exercise into a smaller list representing the skewness.

    Args:
        values_per_exercise (list[list[int]  |  list[float]]): The list of values calculated for each attempted exercise. List of 6 lists, with the final one contaning values from every exercise

    Returns:
        list[int]: A list of 6 ints containing the skewness for each exercise. The 5th item in the list is the skewness for the whole values_per_exercise list
    """
    distributions_per_exercise = []

    for i in range(6):
        if values_per_exercise[i] != []:
            distributions_per_exercise.append(skew(values_per_exercise[i], bias=False))
        else:
            #Adds an empty list if there are no entries in the total_times_per_exercises for a given exercise
            #i.e. if none of the list of participants had attempted a given exercise
            distributions_per_exercise.append([])
    return distributions_per_exercise

def total_per_exercises(values_per_exercise:list[list[int] | list[float]]) -> list[int]:
    return [sum(exercise) for exercise in values_per_exercise]

def overall_total(values_per_exercise:list[list[int] | list[float]]) -> int | float:
    """Converts a list of values for a given metric into an overall total
    e.g. If the number of repeated runs for each attempted exercises was [1,2,3,4], this function would return 10.

    Args:
        values_per_exercise (list[list[int]  |  list[float]]): The list of values (for a given metric) for each given exercise

    Returns:
        int | float: The aggregated total across all exercises
    """
    return sum(values_per_exercise[5])

def highest_value(values_per_exercise:list[list[int] | list[float]]) -> int | float:
    """Gets the highest value for a given metric across all attempted exercises

    Args:
        values_per_exercise (list[list[int]  |  list[float]]): The list of values (for a given metric) for each given exercise

    Returns:
        int | float: The highest value across all exercises
    """
    return max(values_per_exercise[5])